### ISSUE TITLE
Eror when run docker image

### ISSUE THREAD

**Issue by Kohinor46** [kugaevsky/outline-server-arm64#10]
Hi.
I can't run docker image it's crash with error:
```
 E2023-10-08T10:16:19.445Z 11 main.js:33] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
2023-10-08 13:16:19     at Object.openSync (node:fs:582:10)
2023-10-08 13:16:19     at Object.readFileSync (node:fs:458:35)
2023-10-08 13:16:19     at /opt/outline-server/app/main.js:33:12797
2023-10-08 13:16:19     at Generator.next (<anonymous>)
2023-10-08 13:16:19     at o (/opt/outline-server/app/main.js:33:8968)
2023-10-08 13:16:19     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

And when i run command to install and run i get error:
```
sudo SB_IMAGE="kugaevsky/outline-server-arm64" bash -c "$(wget -qO- https://raw.githubusercontent.com/kugaevsky/outline-server-arm64/master/src/server_manager/install_scripts/install_server.sh)"
Unsupported machine type: arm64. Please run this script on a x86_64 machine

Sorry! Something went wrong. If you can't figure this out, please copy and paste all this output into the Outline Manager screen, and send it to us, to see if we can help you.
Full log: /var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/outline_logXXX.hTzeYsIR

```

**Comment by genothomas** [comment]
This works!

> [kugaevsky/outline-server-arm64#3 (comment)](https://github.com/kugaevsky/outline-server-arm64/issues/3#issuecomment-1069800724)

`sudo SB_IMAGE="kugaevsky/outline-server-arm64" bash -c "$(curl -sL "https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh" | sed '/local MACHINE_TYPE/,/fi/{d}')"`

**Comment by Kohinor46** [comment]
Now it's wait at step 
` Waiting for Outline server to be healthy .... `
in containers no errors
<img width="1151" alt="image" src="https://github.com/kugaevsky/outline-server-arm64/assets/52031286/f4ed8e55-fa19-4f1a-bfd7-d89495741526">
